config/routes.rb
Rails.application.routes.draw do
  get 'permissions/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    get 'search', on: :collection
    post 'search', on: :collection
    get 'access', on: :member
    post 'empower', on: :member
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :actions, only: [:index]
  resources :resources, only: [:new, :create, :index]
  resources :permissions, only: [:index] do
    post 'search', on: :collection
  end
  resources :roles, only: [:new, :create, :index, :edit, :update] do
    get 'access', on: :member
    post 'empower', on: :member
  end
end

app/models/user.rb
require 'digest/sha1'

class User < ApplicationRecord
  include Statusable

  attr_accessor :password

  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :username, presence: {message: 'username can\'t be blank'}, uniqueness: {case_sensitive: true}
  validates :email, presence: {message: 'email can\'t be blank'}, uniqueness: {case_sensitive: true}, format: EMAIL_REGEX
  validates :password, presence: {message: 'password can\'t be blank'}, confirmation: true, if: lambda { self.encrypted_password == nil }

  before_save :encrypt_password
  after_save :clear_password

  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :role_permissions, through: :roles
  has_many :permissions, through: :roles

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def authenticate(password)
    BCrypt::Engine.hash_secret(password, self.salt) == self.encrypted_password
  end

  def admin?
    'admin' == self.username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'You have sign up successfully!'
      redirect_to access_user_path(@user)
    else
      flash[:alert] = 'Sign up failed'
      respond_to do |format|
        format.js
      end
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @search_key = params[:search_key]
    @users = User.where("username LIKE ? OR email LIKE ?", "%#{@search_key}%", "%#{@search_key}%")
    respond_to do |format|
      format.html { render 'index' }
      format.js
      format.xml { render xml: @users }
      format.json { render json: @users }
    end
  end

  def edit
    @user = User.find(id)
  end

  def update
    @user = User.find(id)
    if @user.update!(user_params)
      flash[:success] = "Update user #{@user.username} (ID = #{id}) success"
      redirect_to users_path
    else
      flash[:alert] = "Update user #{@user.username} (ID = #{id}) failed"
      respond_to do |format|
        format.js
      end
    end
  end

  def access
    @user = User.find(id)
    @roles = Role.active
    @active_role_ids = @user.user_roles.active.collect(&:role_id)
  end

  def empower
    @user = User.find(id)
    db_role_ids = @user.user_roles.active.collect(&:role_id)

    # inactive user_role
    (db_role_ids - role_ids).each do |role_id|
      UserRole.find_or_create_by(user_id: id, role_id: role_id).inactive!
    end

    # active user_role
    role_ids.each do |role_id|
      UserRole.find_or_create_by(user_id: id, role_id: role_id).active!
    end

    flash[:success] = "Authorize user #{@user.username} (ID = #{id}) success"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def id
    params[:id]
  end

  def role_ids
    (params[:role_ids] || []).collect(&:to_i)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <%= form_group_for(f, :username)%>
  <%= form_group_for(f, :email) %>
  <%= form_group_for(f, :password) %>
  <%= form_group_for(f, :password_confirmation) %>
  <%= f.submit :Signup, class: 'btn btn-primary' %>
<% end %>

app/views/users/_signup.html.erb
<%= form_with(model: user) do |f| %>
  <%= form_group_for(f, :username)%>
  <%= form_group_for(f, :email) %>

  <%= form_group_for(f, :password) do %>
  <%= f.password_field :password, value: user.password, class: "form-control #{'is-invalid' if user.errors[:password].present?}" %>
  <% end %>

  <%= form_group_for(f, :password_confirmation) do %>
  <%= f.password_field :password_confirmation, value: user.password_confirmation, class: "form-control #{'is-invalid' if user.errors[:password_confirmation].present?}" %>
  <% end %>
  <%= f.submit :Submit, class: 'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <th scope='row'><%= user.id %></th>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <% if policy(User).update? %>
    <td>
    <div class="btn-group">
      <%= button_to "Edit", edit_user_path(user), method: :get, local: true, class: 'btn btn-primary' %>
      <%= button_to "Access", access_user_path(user), method: :get, local: true, class: 'btn btn-primary' %>
    </div>
    </td>
  <% end %>
</tr>

app/views/users/access.html.erb
<h1>empower user (ID = <%= @user.id %>, Name = <%= @user.username %>)</h1>

<div id="form_user">
  <%= form_with(url: empower_user_path(@user)) do |f| %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <th>
            <input type="checkbox" class="select-all checkbox" name="select-all" />
          </th>
          <th scope="col">Role ID</th>
          <th scope="col">Role Name</th>
        <thead>

        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td>
              <label style="margin: 0;">
              <%= f.check_box :role_ids, {multiple: true, checked: @active_role_ids.include?(role.id), class: 'select-item'}, role.id, nil %>
              </label>
            </td>
            <td><%= role.id %></td>
            <td><%= link_to role.name, access_role_path(role) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
</div>

<script>
  $(function() {
    $('input.select-all').click(function() {
      var checked = this.checked;
      $('input.select-item').each(function (index, item) {
        item.checked = checked;
      });
    });
  });
</script>

app/views/users/create.js.erb
var div_flash = document.getElementById("flash");
div_flash.innerHTML = "<%= escape_javascript(render 'layouts/flash') %>";
<% flash.delete(:alert) %>

var form_user = document.getElementById('form_user');
form_user.innerHTML = "<%= escape_javascript(render 'form', user: @user) %>";

app/views/users/edit.html.erb
<% @page_tile = "Edit User" %>

<h1>Sign User</h1>

<div id="form_user">
  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<% if policy(User).retrieve? %>
  <%= form_with(url: search_users_path, class: 'form-inline mt-1 mb-1') do |f| %>
    <div class='form-group'>
      <%= f.text_field :search_key, value: @search_key, placeholder: 'Search User', class: 'form-control' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary ml-1' %>
  <% end %>
<% end %>

<table class='table table-striped mt-1 mb-1'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>ID</th>
      <th scope='col'>Username</th>
      <th scope='col'>Email</th>
      <% if policy(User).update? %>
        <th scope="col">Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody id="users">
    <%= render @users %>
  <tbody>
</table>

app/views/users/new.html.erb
<% @page_tile = "Signup" %>
<h1>Sign Up</h1>
<div id="form_user">
  <%= render "signup", user: @user %>
</div>

app/views/users/search.js.erb
var tbody = document.getElementById("users");
tbody.innerHTML = "<%= escape_javascript(render @users) %>";

app/views/users/show.html.erb
<div>
  <p> Username:</br> <%= @user.username %> </p>
  <p> Email:</br> <%= @user.email %> </p>
</div>

app/views/users/update.js.erb
var div_flash = document.getElementById("flash");
div_flash.innerHTML = "<%= escape_javascript(render 'layouts/flash') %>";
<% flash.delete(:alert) %>

var form_user = document.getElementById('form_user');
form_user.innerHTML = "<%= escape_javascript(render 'form', user: @user) %>";