config/routes.rb
Rails.application.routes.draw do
  get 'permissions/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    get 'search', on: :collection
    post 'search', on: :collection
    get 'access', on: :member
    post 'empower', on: :member
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :actions, only: [:index]
  resources :resources, only: [:new, :create, :index]
  resources :permissions, only: [:index] do
    post 'search', on: :collection
  end
  resources :roles, only: [:new, :create, :index, :edit, :update] do
    get 'access', on: :member
    post 'empower', on: :member
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, through: :role_permissions
  belongs_to :action
  belongs_to :resource
  validates :action_id, uniqueness: {scope: :resource_id}

  scope :order_by_resource, -> { order("resources.name DESC") }

  class << self
    def generate(resource)
      Action.all.each do |action|
        create(action_id: action.id, resource_id: resource.id)
      end
    end
  end

  def name
    "#{action.name}_#{resource.name}"
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  def index
    @permissions = Permission.includes(:action, :resource).order_by_resource
  end

  def search
    search_key = params[:search_key]
    @permissions = Permission.eager_load(:action, :resource)
                             .where("actions.name LIKE ? OR resources.name LIKE ?", "%#{search_key}%", "%#{search_key}%")
                             .order_by_resource
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_permission.html.erb
<tr>
  <th scope="row"><%= permission.id %></th>
  <td><%= permission.name %></td>
  <td><%= permission.status %></td>
</tr>

app/views/permissions/index.html.erb
<% if policy(Permission).retrieve? %>
  <%= form_with(url: search_permissions_path, class: 'form-inline mt-1 mb-1') do |f| %>
    <div class='form-group'>
      <%= f.text_field :search_key, value: @search_key, placeholder: 'Search Permission', class: 'form-control' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary ml-1' %>
  <% end %>
<% end %>

<table class="table table-dark table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Permission name</th>
      <th scope="col">Status</th>
    </tr>
  </thead>

  <tbody id="permissions">
    <%= render @permissions %>
  </tbody>
</table>

app/views/permissions/search.js.erb
var tbody = document.getElementById("permissions");
tbody.innerHTML = "<%= escape_javascript(render @permissions) %>";