config/routes.rb
Rails.application.routes.draw do
  get 'permissions/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    get 'search', on: :collection
    post 'search', on: :collection
    get 'access', on: :member
    post 'empower', on: :member
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :actions, only: [:index]
  resources :resources, only: [:new, :create, :index]
  resources :permissions, only: [:index] do
    post 'search', on: :collection
  end
  resources :roles, only: [:new, :create, :index, :edit, :update] do
    get 'access', on: :member
    post 'empower', on: :member
  end
end

app/models/role.rb
class Role < ApplicationRecord
  include Statusable

  has_many :role_permissions
  has_many :permissions, through: :role_permissions

  validates :name, presence: true, uniqueness: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def new
    authorize Role
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:success] = 'Create role success!'
      redirect_to roles_path
    else
      flash[:alert] = 'Create role failed'
      respond_to do |format|
        format.js
      end
    end
  end

  def index
    @roles = Role.all
    @role = Role.new
  end

  def show
    @role = Role.find(id)
  end

  def edit
    @role = Role.find(id)
  end

  def update
    @role = Role.find(id)
    if @role.update(role_params)
      flash[:success] = "Update role (ID = #{id}) success"
      redirect_to roles_path
    else
      flash[:alert] = "Update role (ID = #{id}) failed"
      respond_to do |format|
        format.js
      end
    end
  end

  def access
    @role = Role.find(id)
    @active_ids = @role.role_permissions.active.collect(&:permission_id)
    @permissions = Permission.includes(:action, :resource)
  end

  def empower
    @role = Role.includes(:role_permissions).find(id)
    db_permission_ids = @role.role_permissions.collect { |r_p| r_p.permission_id }

    # inactive [@role, db_permission_ids - permission_ids]
    (db_permission_ids - permission_ids).each do |p_id|
      RolePermission.find_or_create_by(role_id: id, permission_id: p_id).inactive!
    end

    # active [@role, permission_ids]
    permission_ids.each do |p_id|
      RolePermission.find_or_create_by(role_id: id, permission_id: p_id).active!
    end

    redirect_to access_role_path(@role)
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end

  def id
    params[:id]
  end

  def permission_ids
    (params[:permission_ids] || []).collect(&:to_i)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, class: 'form-inline') do |f| %>
  <%= form_group_for(f, :name, label: false)  do %>
    <%= f.text_field(:name, value: role.name, placeholder: 'Create Role', class: "form-control #{ 'is-invalid' if role.errors[:name].present? }") %>
  <% end %>
  <%= f.submit 'Submit', class: 'btn btn-primary ml-1' %>
<% end %>

app/views/roles/_role.html.erb
<tr>
  <th scope='row'><%= role.id %></th>
  <td><%= role.name %></td>
  <td>
  <div class="btn-group">
    <%= button_to "Edit", edit_role_path(role), method: :get, local: true, class: 'btn btn-primary' %>
    <%= button_to "Access", access_role_path(role), method: :get, local: true, class: 'btn btn-primary' %>
  </div>
  </td>
</tr>

app/views/roles/access.html.erb
<h1>Empower role (ID = <%= @role.id %>, Name = <%= @role.name %>)</h1>

<div id="form_role">
  <%= form_with(url: empower_role_path(@role)) do |f| %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <th>
            <input type="checkbox" class="select-all checkbox" name="select-all" />
          </th>
          <th scope="col">ID</th>
          <th scope="col">Resource</th>
          <th scope="col">Action</th>
        <thead>

        <tbody>
          <% @permissions.each do |permission| %>
          <tr>
            <td>
              <label style="margin: 0;">
                <%= f.check_box :permission_ids, {multiple: true, checked: @active_ids.include?(permission.id), class: 'select-item'}, permission.id, nil %>
              </label>
            </td>
            <td><%= permission.id %></td>
            <td><%= permission.resource.name %></td>
            <td><%= permission.action.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
</div>

<script>
  $(function() {
    $('input.select-all').click(function() {
      var checked = this.checked;
      $('input.select-item').each(function (index, item) {
        item.checked = checked;
      });
    });
  });
</script>

app/views/roles/create.js.erb
var div_flash = document.getElementById("flash");
div_flash.innerHTML = "<%= escape_javascript(render 'layouts/flash') %>";
<% flash.delete(:alert) %>

var form_role = document.getElementById('form_role');
form_role.innerHTML = "<%= escape_javascript(render 'form', role: @role) %>";

app/views/roles/edit.html.erb
<h1>Edit role (ID = <%= @role.id %>)</h1>

<div id="form_role">
  <%= render "form", role: @role %>
</div>

app/views/roles/index.html.erb
<div id='form_role' class="mt-1">
  <%= render "form", role: @role if policy(Role).create? %>
</div>

<div class="table-responsive">
  <table class="table table-dark table-hover table-striped mt-1 mb-1 btn-table">
    <caption>List of roles</caption>
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Role name</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody id="roles">
      <%= render @roles %>
    </tbody>
  </table>
</div>

app/views/roles/new.html.erb
<% @page_title = 'Create role' %>

<div id='form_role'>
  <%= render "form", role: @role %>
</div>

app/views/roles/update.js.erb
var div_flash = document.getElementById("flash");
div_flash.innerHTML = "<%= escape_javascript(render 'layouts/flash') %>";
<% flash.delete(:alert) %>

var form_role = document.getElementById('form_role');
form_role.innerHTML = "<%= escape_javascript(render 'form', role: @role) %>";