config/routes.rb
Rails.application.routes.draw do
  get 'permissions/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    get 'search', on: :collection
    post 'search', on: :collection
    get 'access', on: :member
    post 'empower', on: :member
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :actions, only: [:index]
  resources :resources, only: [:new, :create, :index]
  resources :permissions, only: [:index] do
    post 'search', on: :collection
  end
  resources :roles, only: [:new, :create, :index, :edit, :update] do
    get 'access', on: :member
    post 'empower', on: :member
  end
end

app/models/action.rb
class Action < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, through: :role_permissions
  belongs_to :action
  belongs_to :resource
  validates :action_id, uniqueness: {scope: :resource_id}

  scope :order_by_resource, -> { order("resources.name DESC") }

  class << self
    def generate(resource)
      Action.all.each do |action|
        create(action_id: action.id, resource_id: resource.id)
      end
    end
  end

  def name
    "#{action.name}_#{resource.name}"
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  NAME_REGEX = /[A-Za-z][A-Za-z0-9_]+/i
  validates :name, presence: true, uniqueness: true, format: NAME_REGEX
end

app/models/role.rb
class Role < ApplicationRecord
  include Statusable

  has_many :role_permissions
  has_many :permissions, through: :role_permissions

  validates :name, presence: true, uniqueness: true
end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  include Statusable

  belongs_to :role
  belongs_to :permission
  validates :role_id, uniqueness: {scope: :permission_id}

  delegate :name, to: :role, prefix: true
  delegate :name, to: :permission, prefix: true
end

app/models/user.rb
require 'digest/sha1'

class User < ApplicationRecord
  include Statusable

  attr_accessor :password

  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :username, presence: {message: 'username can\'t be blank'}, uniqueness: {case_sensitive: true}
  validates :email, presence: {message: 'email can\'t be blank'}, uniqueness: {case_sensitive: true}, format: EMAIL_REGEX
  validates :password, presence: {message: 'password can\'t be blank'}, confirmation: true, if: lambda { self.encrypted_password == nil }

  before_save :encrypt_password
  after_save :clear_password

  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :role_permissions, through: :roles
  has_many :permissions, through: :roles

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def authenticate(password)
    BCrypt::Engine.hash_secret(password, self.salt) == self.encrypted_password
  end

  def admin?
    'admin' == self.username
  end
end

app/models/user_context.rb
class UserContext
  attr_reader :user, :session

  def initialize(user, session)
    @user, @session = user, session
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  include Statusable

  belongs_to :user
  belongs_to :role
  validates :role_id, uniqueness: {scope: :user_id}

  delegate :name, to: :user, prefix: true
  delegate :name, to: :role, prefix: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :authorized
  
  def index
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice, 'notice' then "alert-info"
      when :success, 'success' then "alert-success"
      when :error, 'error' then "alert-danger"
      when :alert, 'alert' then "alert-danger"
    end
  end
end

app/helpers/form_helper.rb
module FormHelper
  def form_group_for(form, field, opts={}, &block)
    object = form.object

    value         = object[field]
    is_invalid    = object.errors[field].present?
    error_message = object.errors[field].try(:first)

    label       = opts.fetch(:label) { true }
    label_text  = opts.fetch(:label_text) { nil }
    placeholder = opts.fetch(:placeholder) { '' }

    content_tag :div, class: "form-group" do
      concat form.label(field, label_text, class: 'control-label') if label
      if block_given?
        concat capture(&block)
      else
        concat form.text_field(field, value: value, class: "form-control #{'is-invalid' if is_invalid }", placeholder: placeholder)
      end
      concat content_tag(:div, error_message, class: 'invalid-feedback')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |level, msg| %>
  <div class="alert <%= flash_class(level) %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'SSO', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link text-light" %></li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="usersDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Users
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="usersDropdown">
          <%= link_to "Create user", new_user_path, class: 'dropdown-item bg-dark text-light' if policy(User).create? %>
          <%= link_to "User list", users_path, class: 'dropdown-item bg-dark text-light' if policy(User).index? %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to "Roles", roles_path, class: 'nav-link' if policy(Role).index? %>
      </li>

      <li class="nav-item">
        <%= link_to "Resources", resources_path, class: 'nav-link' if policy(Resource).index? %>
      </li>

      <li class="nav-item">
        <%= link_to "Permissions", permissions_path, class: 'nav-link' if policy(Permission).index? %>
      </li>

      <% if is_login? %>
        <li class="nav-item"><%= link_to "Logout", logout_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "#{current_user.email}", user_path(current_user.id), class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Signup", signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || 'SSO'%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash"><%= render 'layouts/flash' %></div>
    <div id="navbar"><%= render 'layouts/navbar' %></div>
    <%= yield %>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource, class: 'form-inline') do |f| %>
  <%= form_group_for(f, :name, label: false) do %>
    <%= f.text_field(:name, value: resource.name, placeholder: 'Create Resource', class: "form-control #{'is-invalid' if resource.errors[:name].present? }")%>
  <% end %>
  <%= f.submit 'Submit', class: 'btn btn-primary ml-1' %>
<% end %>

app/views/resources/_resource.html.erb
<tr>
  <th scope="row"><%= resource.id %></th>
  <td><%= resource.name %></td>
  <td><%= resource.status %></td>
</tr>

app/views/resources/create.js.erb
var div_flash = document.getElementById("flash");
div_flash.innerHTML = "<%= escape_javascript(render 'layouts/flash') %>";
<% flash.delete(:alert) %>

var form_resource = document.getElementById("form_resource");
form_resource.innerHTML = "<%= escape_javascript(render 'form', resource: @resource) %>"

app/views/resources/index.html.erb
<div id="form_resource" class="mt-1">
  <%= render 'form', resource: @resource if policy(Resource).create? %>
</div>

<table class="table table-dark table-striped mt-1">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
    </tr>
  </thead>

  <tbody>
    <%= render @resources %>
  </tbody>
</table>

app/views/resources/new.html.erb
<h1>Create Resource</h1>

<div id="form_resource">
  <%= render 'form', resource: @resource %>
</div>